services:
  # Cliente Frontend React / Vite / Tailwind CSS
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: /
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080/api}
    container_name: finanecuador_frontend_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:5173:80"
