server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Si Traefik envía la ruta completa:
    # /economia/simulador/... -> /...
    location = /economia/simulador {
        rewrite ^ / last;
    }

    location ^~ /economia/simulador/ {
        rewrite ^/economia/simulador/(.*)$ /$1 last;
    }

    # Assets reales de Vite
    location /assets/ {
        try_files $uri =404;
    }

    # React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}
