/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#ccdbf4',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dde9ff',
        'surface-container-highest': '#d5e3fd',
        'on-surface': '#0d1c2f',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#ebf1ff',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#495f82',
        primary: 'var(--color-primary)',
        'on-primary': '#ffffff',
        'primary-container': '#0b2545',
        'on-primary-container': '#778db2',
        'inverse-primary': '#b1c7f0',
        secondary: 'var(--color-secondary)',
        'on-secondary': '#ffffff',
        'secondary-container': '#0266ff',
        'on-secondary-container': '#f9f7ff',
        tertiary: '#00130a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002b1b',
        'on-tertiary-container': '#009f6e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#b1c7f0',
        'on-primary-fixed': '#001c3b',
        'on-primary-fixed-variant': '#314769',
        'secondary-fixed': '#dae1ff',
        'secondary-fixed-dim': '#b3c5ff',
        'on-secondary-fixed': '#001849',
        'on-secondary-fixed-variant': '#003fa4',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        background: '#f8f9ff',
        'on-background': '#0d1c2f',
        'surface-variant': '#d5e3fd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'numeric-hero': ['"JetBrains Mono"', 'monospace'],
        'numeric-data': ['"JetBrains Mono"', 'monospace'],
        'badge-label': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'numeric-hero': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'numeric-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'badge-label': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      }
    },
  },
  plugins: [],
}
